name: Build, Push and Deploy Docker Windows Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: windows-2022  # <--- Use runner Windows!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (Windows)
        run:  
          docker build -t aledomici/desafiofinal-datasentinel:${{ github.sha }} .
          docker tag aledomici/desafiofinal-datasentinel:${{ github.sha }} aledomici/desafiofinal-datasentinel:latest
          docker push aledomici/desafiofinal-datasentinel:${{ github.sha }}
          docker push aledomici/desafiofinal-datasentinel:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Windows via WinRM
        uses: appleboy/winrm-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: Administrator
          password: ${{ secrets.EC2_PASSWORD }}
          script:  
            docker pull aledomici/desafiofinal-datasentinel:${{ github.sha }}
            docker stop desafiofinal-datasentinel || exit 0
            docker rm desafiofinal-datasentinel || exit 0
            docker run -d --name desafiofinal-datasentinel -p 80:80 aledomici/desafiofinal-datasentinel:${{ github.sha }}